### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by TFCAliarcy** [ACGaming/Binnie#1]
I'm having an issue booting the latest version of this fork in that it crashes upon trying to launch.

I'm using a fresh instance of MultiMC with just this mod and forestry

[crash-2023-07-25_18.30.35-client.txt](https://github.com/ACGaming/Binnie/files/12166123/crash-2023-07-25_18.30.35-client.txt)

**Comment by ACGaming** [comment]
Should be solved with f792fc500d46188eac2f91734754746f1041686a.
