### ISSUE TITLE
Possible Crash from binnie's mod

### ISSUE THREAD

**Issue by Mysticpasta1** [ACGaming/Binnie#2]
[crash-2023-08-04_11.23.20-client.txt](https://github.com/ACGaming/Binnie/files/12262755/crash-2023-08-04_11.23.20-client.txt)

**Comment by Mysticpasta1** [comment]
renderlib was the cause of it crashing idk why though

**Comment by Rongmario** [comment]
This seems like it is crashing on the `IBlockAccess` instance being `null`. The instance is retrieved via `IExtendedState` in `BlockDesign#getWorldKey`, just by reading the code I think there may be a chance for it to be `null`, the code is pretty convoluted though and involves a lot of Forestry's API too.

**Comment by ACGaming** [comment]
Good eye, totally overlooked the IBlockAccess instance. Another null check won‘t hurt!
